#!/bin/sh

branch_name=$(git symbolic-ref --short HEAD)
protected_branches="main master"

if echo "$protected_branches" | grep -q "\b$branch_name\b"; then
    echo "Error: Pushing to $branch_name branch is not allowed."
    echo "If you really want to do this, use --no-verify to bypass this pre-push hook."
    exit 1
fi

exit 0
