#!/bin/sh

branch_name=$(git symbolic-ref --short HEAD)
protected_branches="main master"

if echo "$protected_branches" | grep -q "\b$branch_name\b"; then
    echo "Error: Direct commits to $branch_name branch are not allowed."
    echo "Please create a new branch for your changes and submit a pull request."
    exit 1
fi

exit 0
